var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[d]=c.value)},r="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function t(){t=function(){};r.Symbol||(r.Symbol=u)}var v=0;function u(a){return"jscomp_symbol_"+(a||"")+v++}
function w(){t();var a=r.Symbol.iterator;a||(a=r.Symbol.iterator=r.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&p(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return x(this)}});w=function(){}}function x(a){var d=0;return y(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})}function y(a){w();a={next:a};a[r.Symbol.iterator]=function(){return this};return a}function z(a){w();var d=a[Symbol.iterator];return d?d.call(a):x(a)}
for(var C=r,D=["Promise"],E=0;E<D.length-1;E++){var F=D[E];F in C||(C[F]={});C=C[F]}
var G=D[D.length-1],J=C[G],K=function(){function a(b){this.f=0;this.l=void 0;this.c=[];var a=this.i();try{b(a.resolve,a.reject)}catch(g){a.reject(g)}}function d(){this.b=null}if(J)return J;d.prototype.m=function(b){null==this.b&&(this.b=[],this.w());this.b.push(b)};d.prototype.w=function(){var b=this;this.o(function(){b.C()})};var c=r.setTimeout;d.prototype.o=function(b){c(b,0)};d.prototype.C=function(){for(;this.b&&this.b.length;){var b=this.b;this.b=[];for(var a=0;a<b.length;++a){var g=b[a];delete b[a];
try{g()}catch(m){this.A(m)}}}this.b=null};d.prototype.A=function(a){this.o(function(){throw a;})};a.prototype.i=function(){function a(a){return function(b){g||(g=!0,a.call(e,b))}}var e=this,g=!1;return{resolve:a(this.H),reject:a(this.j)}};a.prototype.H=function(b){if(b===this)this.j(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof a)this.I(b);else{var e;a:switch(typeof b){case "object":e=null!=b;break a;case "function":e=!0;break a;default:e=!1}e?this.G(b):this.s(b)}};a.prototype.G=
function(a){var b=void 0;try{b=a.then}catch(g){this.j(g);return}"function"==typeof b?this.J(b,a):this.s(a)};a.prototype.j=function(a){this.u(2,a)};a.prototype.s=function(a){this.u(1,a)};a.prototype.u=function(a,e){if(0!=this.f)throw Error("Cannot settle("+a+", "+e|"): Promise already settled in state"+this.f);this.f=a;this.l=e;this.D()};a.prototype.D=function(){if(null!=this.c){for(var a=this.c,e=0;e<a.length;++e)a[e].call(),a[e]=null;this.c=null}};var h=new d;a.prototype.I=function(a){var b=this.i();
a.g(b.resolve,b.reject)};a.prototype.J=function(a,e){var b=this.i();try{a.call(e,b.resolve,b.reject)}catch(m){b.reject(m)}};a.prototype.then=function(b,e){function g(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(M){d(M)}}:b}var c,d,h=new a(function(a,b){c=a;d=b});this.g(g(b,c),g(e,d));return h};a.prototype["catch"]=function(a){return this.then(void 0,a)};a.prototype.g=function(a,c){function b(){switch(e.f){case 1:a(e.l);break;case 2:c(e.l);break;default:throw Error("Unexpected state: "+
e.f);}}var e=this;null==this.c?h.m(b):this.c.push(function(){h.m(b)})};a.resolve=function(b){return b instanceof a?b:new a(function(a){a(b)})};a.reject=function(b){return new a(function(a,c){c(b)})};a.race=function(b){return new a(function(c,g){for(var e=z(b),d=e.next();!d.done;d=e.next())a.resolve(d.value).g(c,g)})};a.all=function(b){var c=z(b),d=c.next();return d.done?a.resolve([]):new a(function(b,e){function g(a){return function(c){h[a]=c;l--;0==l&&b(h)}}var h=[],l=0;do h.push(void 0),l++,a.resolve(d.value).g(g(h.length-
1),e),d=c.next();while(!d.done)})};a.$jscomp$new$AsyncExecutor=function(){return new d};return a}();K!=J&&null!=K&&p(C,G,{configurable:!0,writable:!0,value:K});
function L(){return function(a){function d(h){if(c[h])return c[h].a;var b=c[h]={a:{},id:h,loaded:!1};a[h].call(b.a,b,b.a,d);b.loaded=!0;return b.a}var c={};d.O=a;d.M=c;d.p="";return d(0)}([function(a,d,c){a.a=c(1)},function(a,d,c){function h(a,c){c=void 0===c?{}:c;return b(a,c)}function b(a,b){a&&(b.url=a);return new Promise(function(a,c){return e(b,function(b,d){return b?c(b):a(d)})})}var e=c(2);d="get put post patch head delete del".split(" ");c=d.length;for(var g={};c--;)g.method=d[c],h["delete"===
g.method?"del":g.method]=function(a){return function(c,d){d=void 0===d?{}:d;d.method=a.method.toUpperCase();return b(c,d)}}(g),g={method:g.method};a.a=h},function(a,d,c){function h(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0}function b(a,b,c){var d=a;q(b)?(c=b,"string"===typeof a&&(d={uri:a})):d=k(b,{uri:a});d.h=c;return d}function e(a,c,d){c=b(a,c,d);return g(c)}function g(a){function b(b){clearTimeout(A);b instanceof Error||(b=Error(""+(b||"Unknown XMLHttpRequest Error")));b.v=0;
var c=g;d||(d=!0,a.h(b,c,void 0))}function c(){if(!k){var b;clearTimeout(A);b=a.K&&void 0===f.status?200:1223===f.status?204:f.status;var c=g,e=null;if(0!==b){f.response?c=f.response:(c=f.responseText)||("document"===f.responseType?c=f.responseXML:(c=204===f.status&&f.responseXML&&"parsererror"===f.responseXML.documentElement.nodeName,c=""!==f.responseType||c?null:f.responseXML));if(H)try{c=JSON.parse(c)}catch(O){}c={body:c,v:b,method:q,headers:{},url:l,F:f};f.getAllResponseHeaders&&(c.headers=N(f.getAllResponseHeaders()))}else e=
Error("Internal XMLHttpRequest Error");b=c.body;d||(d=!0,a.h(e,c,b))}}if("undefined"===typeof a.h)throw Error("callback argument missing");var d=!1,g={body:void 0,headers:{},v:0,method:q,url:l,F:f},f=a.R||null;f||(f=a.N||a.K?new e.XDomainRequest:new e.XMLHttpRequest);var m,k,l=f.url=a.uri||a.url,q=f.method=a.method||"GET",I=a.body||a.data||null,n=f.headers=a.headers||{},B=!!a.P,H=!1,A;"json"in a&&(H=!0,n.accept||n.Accept||(n.Accept="application/json"),"GET"!==q&&"HEAD"!==q&&(n["content-type"]||n["Content-Type"]||
(n["Content-Type"]="application/json"),I=JSON.stringify(a.json)));f.onreadystatechange=function(){4===f.readyState&&c()};f.onload=c;f.onerror=b;f.onprogress=function(){};f.ontimeout=b;f.open(q,l,!B,a.username,a.password);B||(f.withCredentials=!!a.withCredentials);!B&&0<a.timeout&&(A=setTimeout(function(){k=!0;f.abort("timeout");var a=Error("XMLHttpRequest timeout");a.code="ETIMEDOUT";b(a)},a.timeout));if(f.setRequestHeader)for(m in n)n.hasOwnProperty(m)&&f.setRequestHeader(m,n[m]);else if(a.headers&&
!h(a.headers))throw Error("Headers cannot be set on an XDomainRequest object");"responseType"in a&&(f.responseType=a.responseType);"beforeSend"in a&&"function"===typeof a.B&&a.B(f);f.send(I);return f}function m(){}d=c(3);var q=c(4),N=c(5),k=c(8);a.a=e;e.XMLHttpRequest=d.XMLHttpRequest||m;e.XDomainRequest="withCredentials"in new e.XMLHttpRequest?e.XMLHttpRequest:d.XDomainRequest;(function(a,b){for(var c=0;c<a.length;c++)b(a[c])})("get put post patch head delete".split(" "),function(a){e["delete"===
a?"del":a]=function(c,d,e){d=b(c,d,e);d.method=a.toUpperCase();return g(d)}})},function(a,d){(function(c){a.a="undefined"!==typeof window?window:"undefined"!==typeof c?c:"undefined"!==typeof self?self:{}}).call(d,function(){return this}())},function(a){a.a=function(a){var c=d.call(a);return"[object Function]"===c||"function"===typeof a&&"[object RegExp]"!==c||"undefined"!==typeof window&&(a===window.setTimeout||a===window.alert||a===window.confirm||a===window.prompt)};var d=Object.prototype.toString},
function(a,d,c){var h=c(6),b=c(7);a.a=function(a){if(!a)return{};var c={};b(h(a).split("\n"),function(a){var b=a.indexOf(":"),d=h(a.slice(0,b)).toLowerCase();a=h(a.slice(b+1));"undefined"===typeof c[d]?c[d]=a:"[object Array]"===Object.prototype.toString.call(c[d])?c[d].push(a):c[d]=[c[d],a]});return c}},function(a,d){d=a.a=function(a){return a.replace(/^\s*|\s*$/g,"")};d.left=function(a){return a.replace(/^\s*/,"")};d.right=function(a){return a.replace(/\s*$/,"")}},function(a,d,c){var h=c(4);a.a=
function(a,c,d){if(!h(c))throw new TypeError("iterator must be a function");3>arguments.length&&(d=this);if("[object Array]"===b.call(a))for(var g=d,k=0,l=a.length;k<l;k++)e.call(a,k)&&c.call(g,a[k],k,a);else if("string"===typeof a)for(g=d,k=0,l=a.length;k<l;k++)c.call(g,a.charAt(k),k,a);else for(k in g=d,a)e.call(a,k)&&c.call(g,a[k],k,a)};var b=Object.prototype.toString,e=Object.prototype.hasOwnProperty},function(a){a.a=function(){for(var a={},h=0;h<arguments.length;h++){var b=arguments[h],e;for(e in b)d.call(b,
e)&&(a[e]=b[e])}return a};var d=Object.prototype.hasOwnProperty}])}"object"===typeof exports&&"object"===typeof module?module.a=L():"function"===typeof define&&define.L?define("xhr",[],L):"object"===typeof exports?exports.xhr=L():this.xhr=L();